### PR TITLE
Add PNASNet-5-Large

### PR DESCRIPTION
**Pull request by creafz**
PNASNet-5-Large model from [`Progressive Neural Architecture Search`](https://arxiv.org/abs/1712.00559). Weights are ported from [Tensorflow Slim repo](https://github.com/tensorflow/models/tree/master/research/slim) 

PyTorch weights: https://drive.google.com/open?id=1iM3T85bwNlYkv2dCsnfQuSa8TcsFGkfz

For the original Tensorflow model I got `82.858` and `96.182` accuracy values (acc@1 and acc@5 respectively). For the ported version I got `82.736` and `95.992`. However, I am not completely sure that I got those values right. When I tried to run an evaluation for the NASNet-A-Large model to compare accuracy, I got `82.706` / `96.168` accuracy values for the original Tensorflow model, and they slightly differ from `82.693` / `96.163` values that are reported in [README](https://github.com/Cadene/pretrained-models.pytorch#evaluation-on-imagenet). Also when I ran `python examples/imagenet_eval.py --data /path/to/val/images -a nasnetalarge -b 20 -e` command I got `Acc@1 82.506 Acc@5 96.018` and not `Acc@1 82.566 Acc@5 96.086`. Not sure whether that difference could be attributed to the fact that I am using newer versions of libraries that might have some internal changes which affect accuracy (I have Cuda 9 / cuDNN 7 / Tensorflow 1.8 / PyTorch 0.4) or am I doing something wrong.

If you want I can also make a pull request to https://github.com/Cadene/tensorflow-model-zoo.torch with code that converts model weights from a Tensorflow checkpoint to PyTorch.

### CODE REVIEW

**Comment by Cadene** [comment]
pnasnet5large, pytorch 0.4, CUDA8
 * Acc@1 82.736 Acc@5 95.992 

nansnetalarge, pytorch 0.4, CUDA8
 * Acc@1 82.506 Acc@5 96.018

**Comment by Cadene** [comment]
@creafz It seems that pnasnet5large is not compatible with pytorch 0.3. Now that everybody made the switch, I think we don't care.

```
python examples/imagenet_eval.py --data /local/common-data/imagenet_2012/images --arch pnasnet5large -e -b 50
=> creating model 'pnasnet5large'
=> using pre-trained parameters 'imagenet'
Downloading: "http://data.lip6.fr/cadene/pretrainedmodels/pnasnet5large-c2941956.pth" to /home/cadene/.torch/models/pnasnet5large-c2941956.pth
100%|████████████████████████████████████████████████| 345156287/345156287 [00:07<00:00, 48792557.19it/s]
Traceback (most recent call last):
  File "examples/imagenet_eval.py", line 296, in <module>
    main()
  File "examples/imagenet_eval.py", line 68, in main
    pretrained=args.pretrained)
  File "./pretrainedmodels/models/pnasnet.py", line 384, in pnasnet5large
    model.load_state_dict(model_zoo.load_url(settings['url']))
  File "/home/cadene/anaconda3/envs/pytorch03/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 65, in load_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/cadene/anaconda3/envs/pytorch03/lib/python3.6/site-packages/torch/serialization.py", line 261, in load
    return _load(f, map_location, pickle_module)
  File "/home/cadene/anaconda3/envs/pytorch03/lib/python3.6/site-packages/torch/serialization.py", line 409, in _load
    result = unpickler.load()
AttributeError: Can't get attribute '_rebuild_tensor_v2' on <module 'torch._utils' from '/home/cadene/anaconda3/envs/pytorch03/lib/python3.6/site-packages/torch/_utils.py'>
```

**Comment by creafz** [comment]
@Cadene I have rerun the conversion script under PyTorch 0.3.1, the evaluation procedure now successfully finishes under both PyTorch 0.3.1 and PyTorch 0.4.

Here are updated model weights, could you try them?
https://drive.google.com/file/d/1ii0UmNkH5tErlLW2dpKTKcExAJOi5lG2/view?usp=sharing

**Comment by Cadene** [comment]
@creafz Done! https://github.com/Cadene/pretrained-models.pytorch/commit/3acaa88d8145db265b5e1dec03e91eb751b82c74

**Pull request merged**
