### PR TITLE
Add SENet154

### PR DESCRIPTION
**Pull request by creafz**
The port is based on the Caffe version from https://github.com/hujie-frank/SENet

Acc@1 and Acc@5 values for the original Caffe model were taken from https://arxiv.org/abs/1709.01507 (table 4). Acc@1 and Acc@5 values for the ported version were obtained by running imagenet_eval.py.

Weights: https://drive.google.com/open?id=1LfBp-0nWzR2sg_Bxwmw7jyW56Ds0ZPtd

### CODE REVIEW

**Comment by Cadene** [comment]
@creafz Great contribution! Thanks a lot for this pull request. I reproduced your `* Acc@1 81.304 Acc@5 95.498`.

However, `sha256sum senet154-7c8a90cb.pth` gave me the following numbers: `c7b49a05`. How did you obtain your sha256sum?

**Comment by creafz** [comment]
`c7b49a05` is the correct value. I forgot to recalculate hash after I have changed layer name from `fc` to `last_linear`. I have updated the pull request.

**Comment by Cadene** [comment]
Thanks again @creafz :)

**Comment by runzeer** [comment]
There is something something wrong with the senet154 network. When I try to use the SENet154 as the backbone for dectection task. The problem occured as follows:


File "/home/zrz/code/mmdetection-gn_ws/mmdet/models/backbones/senet.py", line 91, in forward

    out = self.se_module(out) + residual

RuntimeError: The size of tensor a (256) must match the size of tensor b (128) at non-singleton dimension 1

It occured in the layer1 forward and the dimention of the out is different from the residual if downsample is none. But how is the downsample implementation. I found the checkpoints file include the downsample value.



--
大   小：2.1K打印 \| 显示邮件原文 \| 导出为eml文件 \| 邮件有乱码？ \| 转发到群邮件 \| 保存到记事本 \| 添加到日历 \| 作为附件转发


收件人：张润泽 <1571718506@qq.com>
--
大   小：2.1K打印 \| 显示邮件原文 \| 导出为eml文件 \| 邮件有乱码？ \| 转发到群邮件 \| 保存到记事本 \| 添加到日历 \| 作为附件转发




收件人：张润泽 <1571718506@qq.com>
--
大   小：2.1K打印 \| 显示邮件原文 \| 导出为eml文件 \| 邮件有乱码？ \| 转发到群邮件 \| 保存到记事本 \| 添加到日历 \| 作为附件转发

**Pull request merged**
